alter table public.teams add column if not exists display_name_es text;

update public.teams set display_name_es = 'México' where code = 'MEX';
update public.teams set display_name_es = 'Sudáfrica' where code = 'RSA';
update public.teams set display_name_es = 'Corea del Sur' where code = 'KOR';
update public.teams set display_name_es = 'República Checa' where code = 'CZE';
update public.teams set display_name_es = 'Canadá' where code = 'CAN';
update public.teams set display_name_es = 'Bosnia y Herzegovina' where code = 'BIH';
update public.teams set display_name_es = 'Catar' where code = 'QAT';
update public.teams set display_name_es = 'Suiza' where code = 'SUI';
update public.teams set display_name_es = 'Brasil' where code = 'BRA';
update public.teams set display_name_es = 'Marruecos' where code = 'MAR';
update public.teams set display_name_es = 'Haití' where code = 'HAI';
update public.teams set display_name_es = 'Escocia' where code = 'SCO';
update public.teams set display_name_es = 'Estados Unidos' where code = 'USA';
update public.teams set display_name_es = 'Paraguay' where code = 'PAR';
update public.teams set display_name_es = 'Australia' where code = 'AUS';
update public.teams set display_name_es = 'Turquía' where code = 'TUR';
update public.teams set display_name_es = 'Alemania' where code = 'GER';
update public.teams set display_name_es = 'Curazao' where code = 'CUW';
update public.teams set display_name_es = 'Costa de Marfil' where code = 'CIV';
update public.teams set display_name_es = 'Ecuador' where code = 'ECU';
update public.teams set display_name_es = 'Países Bajos' where code = 'NED';
update public.teams set display_name_es = 'Japón' where code = 'JPN';
update public.teams set display_name_es = 'Suecia' where code = 'SWE';
update public.teams set display_name_es = 'Túnez' where code = 'TUN';
update public.teams set display_name_es = 'Bélgica' where code = 'BEL';
update public.teams set display_name_es = 'Egipto' where code = 'EGY';
update public.teams set display_name_es = 'Irán' where code = 'IRN';
update public.teams set display_name_es = 'Nueva Zelanda' where code = 'NZL';
update public.teams set display_name_es = 'España' where code = 'ESP';
update public.teams set display_name_es = 'Cabo Verde' where code = 'CPV';
update public.teams set display_name_es = 'Arabia Saudita' where code = 'KSA';
update public.teams set display_name_es = 'Uruguay' where code = 'URU';
update public.teams set display_name_es = 'Francia' where code = 'FRA';
update public.teams set display_name_es = 'Senegal' where code = 'SEN';
update public.teams set display_name_es = 'Irak' where code = 'IRQ';
update public.teams set display_name_es = 'Noruega' where code = 'NOR';
update public.teams set display_name_es = 'Argentina' where code = 'ARG';
update public.teams set display_name_es = 'Argelia' where code = 'ALG';
update public.teams set display_name_es = 'Austria' where code = 'AUT';
update public.teams set display_name_es = 'Jordania' where code = 'JOR';
update public.teams set display_name_es = 'Portugal' where code = 'POR';
update public.teams set display_name_es = 'República Democrática del Congo' where code = 'COD';
update public.teams set display_name_es = 'Uzbekistán' where code = 'UZB';
update public.teams set display_name_es = 'Colombia' where code = 'COL';
update public.teams set display_name_es = 'Inglaterra' where code = 'ENG';
update public.teams set display_name_es = 'Croacia' where code = 'CRO';
update public.teams set display_name_es = 'Ghana' where code = 'GHA';
update public.teams set display_name_es = 'Panamá' where code = 'PAN';
